name: First Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: A comer!
        run: |
          echo "A comer comida en ${{ github.workflow }}"
          echo "desde github ${{ github.event_name }}"
          echo "por ${{ github.actor }}!"

      - name: Veamos mas comida
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"
